### ISSUE TITLE
Substring out of bounds issues

### ISSUE THREAD

**Issue by IanH0073** [leandromartinez98/packmol#1]
Compiling using ifort 16.0.2 on Windows x64, with the build order determined from source analysis tools (`dynamic-debug` is simply a build directory).

    >ifort /check:all /warn:all /standard-semantics /Od /traceback ^
        /Fe:..\dynamic-debug\packmol.exe ^
        /module:..\dynamic-debug\ ^
        /object:..\dynamic-debug\ ^
        sizes.f90 molpa.f90 usegencan.f90 initial.f90 feasy.f90 ^
        pgencan.f90 random.f90 packmol.f90 io.f90 polartocart.f90 ^
        geasy.f90 fgcommon.f90 heuristics.f90 cenmass.f90 title.f90 ^
        gencan.f
    Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 16.0 Build 20160204
    Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
    
    initial.f90(18): remark #7712: This variable has not been used.   [CHECK]
                       movefrac,movebadrandom,check)
    ------------------------------------------^
    initial.f90(546): remark #7712: This variable has not been used.   [PRECISION]
    subroutine restmol(itype,ilubar,n,x,fx,solve,precision,seed)
    ---------------------------------------------^
    initial.f90(546): remark #7712: This variable has not been used.   [SEED]
    subroutine restmol(itype,ilubar,n,x,fx,solve,precision,seed)
    -------------------------------------------------------^
    random.f90(5): remark #7712: This variable has not been used.   [SEED]
    double precision function rnd(seed)
    ------------------------------^
    packmol.f90(709): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
          write(*,"( /&
    -------------------^
    packmol.f90(709): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
          write(*,"( /&
    -------------------^
    packmol.f90(709): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
          write(*,"( /&
    -------------------^
    packmol.f90(792): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
              write(*,"( /, 62('#'),/,                           /,&
    ----------------------------------------------------------------^
    packmol.f90(792): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
              write(*,"( /, 62('#'),/,                           /,&
    ----------------------------------------------------------------^
    io.f90(880): remark #7712: This variable has not been used.   [FIX]
                      pdb,tinker,xyz,moldy,fix,&
    ---------------------------------------^
    fgcommon.f90(511): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
        write(98,"(i10,4(tr2,d13.7))") i, g(i), gbest, error, stepbest
    --------------------------^
    gencan.f(4): remark #7712: This variable has not been used.   [LAMBDA]
          subroutine evalal(n,x,m,lambda,rho,f,flag)
    ------------------------------^
    gencan.f(4): remark #7712: This variable has not been used.   [RHO]
          subroutine evalal(n,x,m,lambda,rho,f,flag)
    -------------------------------------^
    gencan.f(62): remark #7712: This variable has not been used.   [LAMBDA]
          subroutine evalnal(n,x,m,lambda,rho,g,flag)
    -------------------------------^
    gencan.f(62): remark #7712: This variable has not been used.   [RHO]
          subroutine evalnal(n,x,m,lambda,rho,g,flag)
    --------------------------------------^
    gencan.f(125): remark #7712: This variable has not been used.   [N]
          subroutine evalhd(n)
    ------------------------^
    gencan.f(2569): remark #7712: This variable has not been used.   [STEREL]
         +fmin,maxfc,iprint,fcnt,inform,xtrial,d,gamma,sigma1,sigma2,sterel,
    -----------------------------------------------------------------^
    gencan.f(2570): remark #7712: This variable has not been used.   [STEABS]
         +steabs,epsrel,epsabs,infrel,infabs)
    ------^
    gencan.f(2570): remark #7712: This variable has not been used.   [INFREL]
         +steabs,epsrel,epsabs,infrel,infabs)
    ---------------------------^
    gencan.f(2570): remark #7712: This variable has not been used.   [INFABS]
         +steabs,epsrel,epsabs,infrel,infabs)
    ----------------------------------^
    gencan.f(2966): remark #7712: This variable has not been used.   [INFREL]
         +epsabs,infrel,infabs)
    -------------^
    gencan.f(3804): remark #7712: This variable has not been used.   [INFREL]
         +sigma1,sigma2,sterel,steabs,epsrel,epsabs,infrel,infabs)
    ------------------------------------------------^
    gencan.f(3804): remark #7712: This variable has not been used.   [INFABS]
         +sigma1,sigma2,sterel,steabs,epsrel,epsabs,infrel,infabs)
    -------------------------------------------------------^
    gencan.f(5163): remark #7712: This variable has not been used.   [LAMBDA]
          subroutine calchd(nind,ind,x,d,g,n,xc,m,lambda,rho,hd,xtmp,sterel,
    ----------------------------------------------^
    gencan.f(5163): remark #7712: This variable has not been used.   [RHO]
          subroutine calchd(nind,ind,x,d,g,n,xc,m,lambda,rho,hd,xtmp,sterel,
    -----------------------------------------------------^
    gencan.f(5163): remark #7712: This variable has not been used.   [XTMP]
          subroutine calchd(nind,ind,x,d,g,n,xc,m,lambda,rho,hd,xtmp,sterel,
    ------------------------------------------------------------^
    gencan.f(5163): remark #7712: This variable has not been used.   [STEREL]
          subroutine calchd(nind,ind,x,d,g,n,xc,m,lambda,rho,hd,xtmp,sterel,
    -----------------------------------------------------------------^
    gencan.f(5164): remark #7712: This variable has not been used.   [STEABS]
         +steabs,inform)
    ------^
    gencan.f(5164): remark #7712: This variable has not been used.   [INFORM]
         +steabs,inform)
    -------------^

As long as the unused variables are expected, then the warnings appear mostly 
harmless, assuming the potential for output fields full of asterisks is acceptable.  

Then running using the water and urea example from http://www.ime.unicamp.br/~martinez/packmol/examples/mixture-comment.inp

    >dynamic-debug\packmol.exe < mixture-comment.inp
    ##############################################################

     PACKMOL - Packing optimization for the automated
     generation of starting configurations for
     molecular dynamics.

                                              Version 16.070.3

    ##############################################################

      Packmol must be run with: packmol < inputfile.inp

      Userguide at: www.ime.unicamp.br/~martinez/packmol

      Reading input file... (Control-C aborts)
    forrtl: severe (408): fort: (12): Variable RECORD has substring ending point 201 which is greater than the variable length of 200

    Image              PC                Routine            Line        Source
    packmol.exe        000000013F507C3E  Unknown               Unknown  Unknown
    packmol.exe        000000013F4619EA  GETKEY                   1727  io.f90
    packmol.exe        000000013F469BAF  GETINP                    108  io.f90
    packmol.exe        000000013F44C276  MAIN__                    105  packmol.f90
    packmol.exe        000000013F5A050E  Unknown               Unknown  Unknown
    packmol.exe        000000013F585EBF  Unknown               Unknown  Unknown
    kernel32.dll       00000000779C59ED  Unknown               Unknown  Unknown
    ntdll.dll          0000000077AFB371  Unknown               Unknown  Unknown

This is associated with the code stretch (in io.f90 around line 1727 as indicated above):

    do while(record(i:i).gt.' '.and.i.le.200)
      i = i + 1
    end do

where record is a CHARACTER(200) variable.  Fortran does not define the order of operand evaluation (nor require short circuiting logical operators), so that means that if `i` has the value 201, the substring reference `record(i:i)` may still be evaluated even if the second operand to `.and.` is evaluated to be false.

(Whether a problem is observable will depend on the compiler and compile options used.)

What was perhaps intended was something like:

    do while (i .le. len(record))
      if (record(i:i) > '') exit
      i = i + 1
    end do

When the loop ends, i will either be the index of a character "less than or equal to blank" in `record`, or it will be one past the end of record.  **Note** that subsequent code to that loop expects that `i` is within the bounds of `record`!  A complete fix requires the behaviour of this subsequent code to be examined.

The greater-than comparison with an all blank string is suspicious - I don't see why the program would want to depend on the collation sequence of the processor in that way (Perhaps the test is to cover both blank and tab?  If so - better to make that explicit).

    if (is_whitespace(record(i:i))) exit

    function is_whitespace(ch)
      character, intent(in) :: ch
      logical :: is_whitespace
      is_whitespace = (ch == '') .or. (ch == achar(9)) ! .or. whatever else...
    end function is_whitespace

The inappropriate mixing of a test against string length with the substringing itself appears in a few places - I gave up after fixing three or so.

**Comment by leandromartinez98** [comment]
Thank you IanH, I fixed the bug by changing the loop to " ... .and. i .lt. 200 " instead of ".le.". The code that follows is fine with that change.

**Comment by leandromartinez98** [comment]
The suggestion of the "is_whitespace" function is interesting. I will think of including that, although I never had issues with that comparison. Thank you.
