### ISSUE TITLE
Build failure with gfortran 7.1

### ISSUE THREAD

**Issue by jonchang** [leandromartinez98/packmol#5]
Hi, I'm a maintainer at Homebrew/science where we are recently upgraded gcc to 7.1 and are repackaging software that depends on it. Currently packmol fails to build on all versions of macOS with the following error:

```
random.f90:32:23:

   call random_seed(put=seed)
                       1
Error: Size of 'put' argument of 'random_seed' intrinsic at (1) too small (12/33)
make: *** [random.o] Error 1
make: *** Waiting for unfinished jobs....
```

This portion of `random.f90` is where the build error occurs and changing `seed(12)` to `seed(33)` seems to help:

```fortran
subroutine init_random_number(iseed)
  integer :: i, seed(33), iseed
  do i = 1, 12
    seed(i) = i*iseed
  end do
  call random_seed(put=seed)
  return
end subroutine init_random_number
```

**Comment by fxcoudert** [comment]
`RANDOM_SEED` should be first called with the `SIZE` argument to determine the necessary size for the seed array.

**Comment by leandromartinez98** [comment]
Thank you very much you all. Fixed now. the new initialization gets the size of seed as indicated.
