### ISSUE TITLE
Licensing under more permissive license?

### ISSUE THREAD

**Issue by davidlmobley** [leandromartinez98/packmol#8]
Would you have any interest in releasing this under a more permissive license in addition to or instead of GPL?

The background of my request is this: We're working on some large-scale automation of simulations with OpenMM (partly for OpenEye's Orion platform, but also more generally, e.g. see https://github.com/oess/openmm_orion and https://github.com/oess/oeommtools). One of the intended audiences is the pharmaceutical industry, but it will also enable a lot of academic research (and OpenEye's tools are free for academics). As you can see, the work we're doing is already open source under a permissive license and we are contributing back to the community -- but because of IP concerns of the pharma industry, we basically can't use software which is under a GPL license as part of this initiative. 

This leads us to the present question, since to use `packmol` as part of our initiative (as we'd like to) we either need you to release under a more permissive license (such as MIT, BSD-3, or MAYBE LGPL) or we'll have to find a replacement for it or write our own "equivalent" software.

**Comment by davidlmobley** [comment]
In this context, it's perhaps worth noting that are a fairly wide variety of "standard" computational tools in the Python community which have, for similar reasons, gone with licenses like those noted here. For example, `numpy`, `scipy`, `dask`, `matplotlib`, `pandas`, etc. are all BSD-3 if I remember correctly. This helps them build up their user ecosystem/community including commercial people (who may have IP concerns or be otherwise unwilling to base other tools on GPL software out of fear of "contamination") as well as academics. While I support the "spirit" of GPL (wanting users/community to contribute back) my experience in practice so far is that it just means that a significant chunk of the potential user base is going to find other software to use or build their own because of these types of issues.

**Comment by leandromartinez98** [comment]
Dear David,
At this point I could not change the license because the code includes GENCAN as the optimization method, that one being distributed under the GPL license. I can ask  GENCAN developers if they are willing to change the license themselves, though, I will return to you whenever I have a response.

**Comment by leandromartinez98** [comment]
Dear David. We changed the license to MIT. I hope that helps. I just changed the license files and removed references to the GPL license. Please tell me if that is not enough.

**Comment by davidlmobley** [comment]
Cool, thanks so much!

@nividic -- take note!

**Comment by davidlmobley** [comment]
I feel like I should give you some more context, since you're helping us out. Here's an example of the kind of thing we like PackMol for -- we have some wrapper stuff for it here (https://github.com/mobleylab/solvationtoolkit) so you can easily create a mixture of arbitrary organic solvent/solute combinations with input files for various different simulation packages.

**Comment by leandromartinez98** [comment]
Thank you David. One question: I see there that you install packmol "via omnia channel on conda". The other issue open for Packmol is that of someone asking if I could make packmol installable through "conda". Does that mean that you have already done that? Does it keep the package updated? Can that be shared, such that I can solve the other issue? (https://github.com/leandromartinez98/packmol/issues/6)

**Comment by davidlmobley** [comment]
Great question. Let me answer this on #6 . :)
